import type { Customer } from "~/types/customer";
import { daysAgo } from "./utils";

export const customers: Customer[] = [
  {
    id: "cust-horizon",
    user_id: "usr-105",
    company_name: "Horizon Build Group",
    contact_name: "Aria Nolan",
    phone: "+1-415-555-0131",
    email: "aria@horizonbuild.com",
    billing_address: "240 Market St, San Francisco, CA",
    shipping_address: "240 Market St, San Francisco, CA",
    created_at: daysAgo(320),
    updated_at: daysAgo(7),
  },
  {
    id: "cust-ironclad",
    user_id: "usr-204",
    company_name: "Ironclad Structures",
    contact_name: "Mateo Singh",
    phone: "+1-303-555-0172",
    email: "mateo@ironcladstructures.com",
    billing_address: "801 Blake St, Denver, CO",
    shipping_address: "801 Blake St, Denver, CO",
    created_at: daysAgo(280),
    updated_at: daysAgo(5),
  },
  {
    id: "cust-lakeview",
    user_id: "usr-311",
    company_name: "Lakeview Contractors",
    contact_name: "Sofia Ramos",
    phone: "+1-847-555-0199",
    email: "sofia@lakeviewco.com",
    billing_address: "51 Harbor Rd, Evanston, IL",
    shipping_address: "68 Harbor Rd, Evanston, IL",
    created_at: daysAgo(260),
    updated_at: daysAgo(4),
  },
  {
    id: "cust-northline",
    user_id: "usr-402",
    company_name: "Northline Civil",
    contact_name: "Connor Hayes",
    phone: "+1-612-555-0156",
    email: "connor@northlinecivil.com",
    billing_address: "1210 Lake St, Minneapolis, MN",
    shipping_address: "1210 Lake St, Minneapolis, MN",
    created_at: daysAgo(210),
    updated_at: daysAgo(6),
  },
  {
    id: "cust-summit",
    user_id: "usr-508",
    company_name: "Summit Infrastructure",
    contact_name: "Elena Park",
    phone: "+1-702-555-0184",
    email: "elena@summitinfra.com",
    billing_address: "610 Canyon Blvd, Las Vegas, NV",
    shipping_address: "610 Canyon Blvd, Las Vegas, NV",
    created_at: daysAgo(190),
    updated_at: daysAgo(3),
  },
  {
    id: "cust-redwood",
    user_id: "usr-612",
    company_name: "Redwood Builders",
    contact_name: "Marcus Long",
    phone: "+1-916-555-0148",
    email: "marcus@redwoodbuilders.com",
    billing_address: "20 Sierra Ave, Sacramento, CA",
    shipping_address: "20 Sierra Ave, Sacramento, CA",
    created_at: daysAgo(175),
    updated_at: daysAgo(2),
  },
  {
    id: "cust-urbanrise",
    user_id: "usr-703",
    company_name: "UrbanRise Developments",
    contact_name: "Jia Wei",
    phone: "+1-212-555-0168",
    email: "jia@urbanrise.dev",
    billing_address: "9 Hudson St, New York, NY",
    shipping_address: "91 Park Ave, New York, NY",
    created_at: daysAgo(160),
    updated_at: daysAgo(6),
  },
  {
    id: "cust-canyon",
    user_id: "usr-812",
    company_name: "CanyonWorks",
    contact_name: "Ivy Chen",
    phone: "+1-480-555-0194",
    email: "ivy@canyonworks.com",
    billing_address: "45 Mesa Rd, Scottsdale, AZ",
    shipping_address: "45 Mesa Rd, Scottsdale, AZ",
    created_at: daysAgo(150),
    updated_at: daysAgo(5),
  },
];
