import type { Delivery } from "~/types/delivery";
import { daysAgo, daysFromNow } from "./utils";

export const deliveries: Delivery[] = [
  {
    id: "del-2001",
    order_id: "ord-1001",
    driver_id: "drv-miles",
    vehicle_number: "TRK-204",
    status: "delivered",
    scheduled_at: daysAgo(1),
    delivered_at: daysAgo(0),
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
  },
  {
    id: "del-2002",
    order_id: "ord-1002",
    driver_id: "drv-alicia",
    vehicle_number: "TRK-118",
    status: "in_transit",
    scheduled_at: daysAgo(0),
    delivered_at: null,
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: "del-2003",
    order_id: "ord-1003",
    driver_id: null,
    vehicle_number: null,
    status: "scheduled",
    scheduled_at: daysFromNow(1),
    delivered_at: null,
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: "del-2004",
    order_id: "ord-1004",
    driver_id: "drv-eric",
    vehicle_number: "TRK-310",
    status: "delivered",
    scheduled_at: daysAgo(2),
    delivered_at: daysAgo(1),
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: "del-2005",
    order_id: "ord-1006",
    driver_id: "drv-priya",
    vehicle_number: "VAN-45",
    status: "scheduled",
    scheduled_at: daysFromNow(2),
    delivered_at: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
  },
  {
    id: "del-2006",
    order_id: "ord-1008",
    driver_id: "drv-owen",
    vehicle_number: "TRK-522",
    status: "delivered",
    scheduled_at: daysAgo(8),
    delivered_at: daysAgo(8),
    created_at: daysAgo(9),
    updated_at: daysAgo(8),
  },
  {
    id: "del-2007",
    order_id: "ord-1010",
    driver_id: "drv-lina",
    vehicle_number: "TRK-287",
    status: "delivered",
    scheduled_at: daysAgo(11),
    delivered_at: daysAgo(10),
    created_at: daysAgo(12),
    updated_at: daysAgo(10),
  },
];
