import type { Driver } from "~/types/driver";
import { daysAgo } from "./utils";

export const drivers: Driver[] = [
  {
    id: "drv-miles",
    name: "Miles Carter",
    phone: "+1-503-555-0121",
    email: "miles.carter@zoomwide.com",
    license_number: "LIC-OR-49281",
    vehicle_number: "TRK-204",
    created_at: daysAgo(210),
    updated_at: daysAgo(5),
  },
  {
    id: "drv-alicia",
    name: "Alicia Park",
    phone: "+1-415-555-0189",
    email: "alicia.park@zoomwide.com",
    license_number: "LIC-CA-77410",
    vehicle_number: "TRK-118",
    created_at: daysAgo(190),
    updated_at: daysAgo(4),
  },
  {
    id: "drv-eric",
    name: "Eric Dalton",
    phone: "+1-312-555-0197",
    email: "eric.dalton@zoomwide.com",
    license_number: "LIC-IL-56022",
    vehicle_number: "TRK-310",
    created_at: daysAgo(175),
    updated_at: daysAgo(3),
  },
  {
    id: "drv-priya",
    name: "Priya Nair",
    phone: "+1-602-555-0174",
    email: "priya.nair@zoomwide.com",
    license_number: "LIC-AZ-88391",
    vehicle_number: "VAN-45",
    created_at: daysAgo(160),
    updated_at: daysAgo(2),
  },
  {
    id: "drv-owen",
    name: "Owen Brooks",
    phone: "+1-206-555-0143",
    email: "owen.brooks@zoomwide.com",
    license_number: "LIC-WA-23018",
    vehicle_number: "TRK-522",
    created_at: daysAgo(150),
    updated_at: daysAgo(2),
  },
  {
    id: "drv-lina",
    name: "Lina Ortega",
    phone: "+1-702-555-0176",
    email: "lina.ortega@zoomwide.com",
    license_number: "LIC-NV-66503",
    vehicle_number: "TRK-287",
    created_at: daysAgo(140),
    updated_at: daysAgo(1),
  },
];
