import type { InventoryLog } from "~/types/inventory";
import { daysAgo } from "./utils";

export const inventoryLogs: InventoryLog[] = [
  {
    id: "inv-4001",
    product_id: "prod-conc-25mpa",
    movement_type: "in",
    quantity_change: 40,
    reference_type: "purchase_order",
    reference_id: "po-9001",
    note: "Restock for slab pours.",
    created_by: "usr-002",
    created_at: daysAgo(0),
  },
  {
    id: "inv-4002",
    product_id: "prod-conc-bag",
    movement_type: "out",
    quantity_change: -120,
    reference_type: "order",
    reference_id: "ord-1001",
    note: "Fulfilled bagged cement order.",
    created_by: "usr-001",
    created_at: daysAgo(0),
  },
  {
    id: "inv-4003",
    product_id: "prod-rebar-16",
    movement_type: "in",
    quantity_change: 80,
    reference_type: "purchase_order",
    reference_id: "po-9002",
    note: "Rebar restock for upcoming jobs.",
    created_by: "usr-003",
    created_at: daysAgo(1),
  },
  {
    id: "inv-4004",
    product_id: "prod-lumber-2x4",
    movement_type: "out",
    quantity_change: -60,
    reference_type: "order",
    reference_id: "ord-1008",
    note: "Shipped framing lumber.",
    created_by: "usr-002",
    created_at: daysAgo(2),
  },
  {
    id: "inv-4005",
    product_id: "prod-drywall-12",
    movement_type: "adjustment",
    quantity_change: -12,
    reference_type: "cycle_count",
    reference_id: "cc-121",
    note: "Damaged sheets removed.",
    created_by: "usr-004",
    created_at: daysAgo(3),
  },
  {
    id: "inv-4006",
    product_id: "prod-pvc-110",
    movement_type: "in",
    quantity_change: 200,
    reference_type: "purchase_order",
    reference_id: "po-9005",
    note: "Bulk PVC restock.",
    created_by: "usr-002",
    created_at: daysAgo(4),
  },
  {
    id: "inv-4007",
    product_id: "prod-wire-10",
    movement_type: "out",
    quantity_change: -20,
    reference_type: "order",
    reference_id: "ord-1006",
    note: "Electrical kit allocation.",
    created_by: "usr-003",
    created_at: daysAgo(5),
  },
  {
    id: "inv-4008",
    product_id: "prod-adhesive",
    movement_type: "adjustment",
    quantity_change: 15,
    reference_type: "cycle_count",
    reference_id: "cc-128",
    note: "Overcount correction.",
    created_by: "usr-001",
    created_at: daysAgo(6),
  },
];
