import type { Payment } from "~/types/payment";
import { daysAgo } from "./utils";

export const payments: Payment[] = [
  {
    id: "pay-3001",
    order_id: "ord-1001",
    amount: 343,
    method: "bank_transfer",
    status: "paid",
    transaction_ref: "TXN-884392",
    paid_at: daysAgo(0),
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: "pay-3002",
    order_id: "ord-1002",
    amount: 4065,
    method: "bank_transfer",
    status: "pending",
    transaction_ref: "TXN-884401",
    paid_at: null,
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: "pay-3003",
    order_id: "ord-1004",
    amount: 2984,
    method: "card",
    status: "paid",
    transaction_ref: "TXN-882901",
    paid_at: daysAgo(1),
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: "pay-3004",
    order_id: "ord-1006",
    amount: 1910,
    method: "bank_transfer",
    status: "pending",
    transaction_ref: "TXN-881720",
    paid_at: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(4),
  },
  {
    id: "pay-3005",
    order_id: "ord-1008",
    amount: 1196,
    method: "cash",
    status: "paid",
    transaction_ref: "TXN-879122",
    paid_at: daysAgo(9),
    created_at: daysAgo(9),
    updated_at: daysAgo(9),
  },
  {
    id: "pay-3006",
    order_id: "ord-1010",
    amount: 2348,
    method: "bank_transfer",
    status: "paid",
    transaction_ref: "TXN-876540",
    paid_at: daysAgo(11),
    created_at: daysAgo(12),
    updated_at: daysAgo(11),
  },
];
