import type { Supplier } from "~/types/supplier";
import { daysAgo } from "./utils";

export const suppliers: Supplier[] = [
  {
    id: "sup-atlas",
    name: "Atlas Aggregates",
    contact_name: "Kim Warren",
    phone: "+1-312-555-0108",
    email: "kwarren@atlasagg.com",
    address: "102 Quarry Rd, Joliet, IL",
    created_at: daysAgo(240),
    updated_at: daysAgo(14),
  },
  {
    id: "sup-steelworks",
    name: "SteelWorks Co.",
    contact_name: "Dante Price",
    phone: "+1-513-555-0183",
    email: "dprice@steelworks.co",
    address: "77 Foundry Ave, Cincinnati, OH",
    created_at: daysAgo(220),
    updated_at: daysAgo(9),
  },
  {
    id: "sup-pineridge",
    name: "Pine Ridge Timber",
    contact_name: "Sasha Lee",
    phone: "+1-541-555-0162",
    email: "sasha.lee@pineridge.com",
    address: "14 Mill Lane, Eugene, OR",
    created_at: daysAgo(210),
    updated_at: daysAgo(11),
  },
  {
    id: "sup-blueflow",
    name: "BlueFlow Plumbing",
    contact_name: "Marco Patel",
    phone: "+1-904-555-0116",
    email: "mpatel@blueflow.io",
    address: "500 Harbor Dr, Jacksonville, FL",
    created_at: daysAgo(195),
    updated_at: daysAgo(6),
  },
  {
    id: "sup-voltedge",
    name: "VoltEdge Electric",
    contact_name: "Hannah Boyd",
    phone: "+1-602-555-0144",
    email: "hboyd@voltedge.com",
    address: "2700 Signal Pkwy, Phoenix, AZ",
    created_at: daysAgo(180),
    updated_at: daysAgo(4),
  },
  {
    id: "sup-primefin",
    name: "Prime Finishes",
    contact_name: "Leo Grant",
    phone: "+1-206-555-0192",
    email: "leo@primefinishes.com",
    address: "88 Cascade Blvd, Seattle, WA",
    created_at: daysAgo(170),
    updated_at: daysAgo(7),
  },
];
